chestWindow:  Window {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: 5,
  type: 'minecraft:generic_9x6',
  title: '{"translate":"container.chestDouble"}',
  slots: [
    Item {
      type: 367,
      count: 39,
      metadata: 0,
      nbt: null,
      name: 'coal_block',
      displayName: 'Block of Coal',
      stackSize: 64,
      slot: 0
    },
    Item {
      type: 137,
      count: 32,
      metadata: 0,
      nbt: null,
      name: 'iron_block',
      displayName: 'Block of Iron',
      stackSize: 64,
      slot: 1
    },
    Item {
      type: 136,
      count: 14,
      metadata: 0,
      nbt: null,
      name: 'gold_block',
      displayName: 'Block of Gold',
      stackSize: 64,
      slot: 2
    },
    Item {
      type: 182,
      count: 26,
      metadata: 0,
      nbt: null,
      name: 'diamond_block',
      displayName: 'Block of Diamond',
      stackSize: 64,
      slot: 3
    },
    Item {
      type: 79,
      count: 46,
      metadata: 0,
      nbt: null,
      name: 'lapis_block',
      displayName: 'Lapis Lazuli Block',
      stackSize: 64,
      slot: 4
    },
    Item {
      type: 321,
      count: 56,
      metadata: 0,
      nbt: null,
      name: 'redstone_block',
      displayName: 'Block of Redstone',
      stackSize: 64,
      slot: 5
    },
    Item {
      type: 4,
      count: 17,
      metadata: 0,
      nbt: null,
      name: 'diorite',
      displayName: 'Diorite',
      stackSize: 64,
      slot: 6
    },
    Item {
      type: 2,
      count: 11,
      metadata: 0,
      nbt: null,
      name: 'granite',
      displayName: 'Granite',
      stackSize: 64,
      slot: 7
    },
    Item {
      type: 6,
      count: 28,
      metadata: 0,
      nbt: null,
      name: 'andesite',
      displayName: 'Andesite',
      stackSize: 64,
      slot: 8
    },
    null,
    null,
    Item {
      type: 580,
      count: 36,
      metadata: 0,
      nbt: null,
      name: 'gold_ingot',
      displayName: 'Gold Ingot',
      stackSize: 64,
      slot: 11
    },
    Item {
      type: 578,
      count: 38,
      metadata: 0,
      nbt: null,
      name: 'diamond',
      displayName: 'Diamond',
      stackSize: 64,
      slot: 12
    },
    Item {
      type: 695,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'lapis_lazuli',
      displayName: 'Lapis Lazuli',
      stackSize: 64,
      slot: 13
    },
    Item {
      type: 665,
      count: 10,
      metadata: 0,
      nbt: null,
      name: 'redstone',
      displayName: 'Redstone Dust',
      stackSize: 64,
      slot: 14
    },
    null,
    Item {
      type: 32,
      count: 27,
      metadata: 0,
      nbt: null,
      name: 'gravel',
      displayName: 'Gravel',
      stackSize: 64,
      slot: 16
    },
    Item {
      type: 9,
      count: 9,
      metadata: 0,
      nbt: null,
      name: 'dirt',
      displayName: 'Dirt',
      stackSize: 64,
      slot: 17
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    Item {
      type: 14,
      count: 3,
      metadata: 0,
      nbt: null,
      name: 'cobblestone',
      displayName: 'Cobblestone',
      stackSize: 64,
      slot: 26
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    Item {
      type: 39,
      count: 24,
      metadata: 0,
      nbt: null,
      name: 'birch_log',
      displayName: 'Birch Log',
      stackSize: 64,
      slot: 42
    },
    Item {
      type: 37,
      count: 47,
      metadata: 0,
      nbt: null,
      name: 'oak_log',
      displayName: 'Oak Log',
      stackSize: 64,
      slot: 43
    },
    Item {
      type: 573,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'apple',
      displayName: 'Apple',
      stackSize: 64,
      slot: 44
    },
    null,
    null,
    null,
    Item {
      type: 646,
      count: 54,
      metadata: 0,
      nbt: null,
      name: 'flint',
      displayName: 'Flint',
      stackSize: 64,
      slot: 48
    },
    Item {
      type: 613,
      count: 28,
      metadata: 0,
      nbt: null,
      name: 'stick',
      displayName: 'Stick',
      stackSize: 64,
      slot: 49
    },
    null,
    Item {
      type: 25,
      count: 12,
      metadata: 0,
      nbt: null,
      name: 'birch_sapling',
      displayName: 'Birch Sapling',
      stackSize: 64,
      slot: 51
    },
    Item {
      type: 23,
      count: 18,
      metadata: 0,
      nbt: null,
      name: 'oak_sapling',
      displayName: 'Oak Sapling',
      stackSize: 64,
      slot: 52
    },
    Item {
      type: 619,
      count: 13,
      metadata: 0,
      nbt: null,
      name: 'wheat_seeds',
      displayName: 'Wheat Seeds',
      stackSize: 64,
      slot: 53
    },
    Item {
      type: 613,
      count: 5,
      metadata: 0,
      nbt: null,
      name: 'stick',
      displayName: 'Stick',
      stackSize: 64,
      slot: 54
    },
    Item {
      type: 579,
      count: 21,
      metadata: 0,
      nbt: null,
      name: 'iron_ingot',
      displayName: 'Iron Ingot',
      stackSize: 64,
      slot: 55
    },
    Item {
      type: 17,
      count: 15,
      metadata: 0,
      nbt: null,
      name: 'birch_planks',
      displayName: 'Birch Planks',
      stackSize: 64,
      slot: 56
    },
    Item {
      type: 590,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'stone_pickaxe',
      displayName: 'Stone Pickaxe',
      stackSize: 1,
      slot: 57
    },
    Item {
      type: 588,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'stone_sword',
      displayName: 'Stone Sword',
      stackSize: 1,
      slot: 58
    },
    Item {
      type: 39,
      count: 64,
      metadata: 0,
      nbt: null,
      name: 'birch_log',
      displayName: 'Birch Log',
      stackSize: 64,
      slot: 59
    },
    Item {
      type: 14,
      count: 64,
      metadata: 0,
      nbt: null,
      name: 'cobblestone',
      displayName: 'Cobblestone',
      stackSize: 64,
      slot: 60
    },
    Item {
      type: 576,
      count: 10,
      metadata: 0,
      nbt: null,
      name: 'coal',
      displayName: 'Coal',
      stackSize: 64,
      slot: 61
    },
    Item {
      type: 4,
      count: 11,
      metadata: 0,
      nbt: null,
      name: 'diorite',
      displayName: 'Diorite',
      stackSize: 64,
      slot: 62
    },
    Item {
      type: 111,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'dandelion',
      displayName: 'Dandelion',
      stackSize: 64,
      slot: 63
    },
    Item {
      type: 592,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'stone_hoe',
      displayName: 'Stone Hoe',
      stackSize: 1,
      slot: 64
    },
    Item {
      type: 598,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'iron_sword',
      displayName: 'Iron Sword',
      stackSize: 1,
      slot: 65
    },
    Item {
      type: 602,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'iron_hoe',
      displayName: 'Iron Hoe',
      stackSize: 1,
      slot: 66
    },
    Item {
      type: 665,
      count: 5,
      metadata: 0,
      nbt: null,
      name: 'redstone',
      displayName: 'Redstone Dust',
      stackSize: 64,
      slot: 67
    },
    Item {
      type: 171,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'torch',
      displayName: 'Torch',
      stackSize: 64,
      slot: 68
    },
    Item {
      type: 6,
      count: 5,
      metadata: 0,
      nbt: null,
      name: 'andesite',
      displayName: 'Andesite',
      stackSize: 64,
      slot: 69
    },
    Item {
      type: 14,
      count: 5,
      metadata: 0,
      nbt: null,
      name: 'cobblestone',
      displayName: 'Cobblestone',
      stackSize: 64,
      slot: 70
    },
    Item {
      type: 321,
      count: 2,
      metadata: 0,
      nbt: null,
      name: 'redstone_block',
      displayName: 'Block of Redstone',
      stackSize: 64,
      slot: 71
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    Item {
      type: 589,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'stone_shovel',
      displayName: 'Stone Shovel',
      stackSize: 1,
      slot: 82
    },
    Item {
      type: 39,
      count: 3,
      metadata: 0,
      nbt: null,
      name: 'birch_log',
      displayName: 'Birch Log',
      stackSize: 64,
      slot: 83
    },
    Item {
      type: 601,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'iron_axe',
      displayName: 'Iron Axe',
      stackSize: 1,
      slot: 84
    },
    Item {
      type: 599,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'iron_shovel',
      displayName: 'Iron Shovel',
      stackSize: 1,
      slot: 85
    },
    Item {
      type: 591,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'stone_axe',
      displayName: 'Stone Axe',
      stackSize: 1,
      slot: 86
    },
    Item {
      type: 600,
      count: 1,
      metadata: 0,
      nbt: [Object],
      name: 'iron_pickaxe',
      displayName: 'Iron Pickaxe',
      stackSize: 1,
      slot: 87
    },
    Item {
      type: 14,
      count: 64,
      metadata: 0,
      nbt: null,
      name: 'cobblestone',
      displayName: 'Cobblestone',
      stackSize: 64,
      slot: 88
    },
    null
  ],
  inventoryStart: 54,
  inventoryEnd: 90,
  craftingResultSlot: -1,
  requiresConfirmation: true,
  selectedItem: null,
  [Symbol(kCapture)]: false
}
chest.items():  [
  Item {
    type: 367,
    count: 39,
    metadata: 0,
    nbt: null,
    name: 'coal_block',
    displayName: 'Block of Coal',
    stackSize: 64,
    slot: 0
  },
  Item {
    type: 137,
    count: 32,
    metadata: 0,
    nbt: null,
    name: 'iron_block',
    displayName: 'Block of Iron',
    stackSize: 64,
    slot: 1
  },
  Item {
    type: 136,
    count: 14,
    metadata: 0,
    nbt: null,
    name: 'gold_block',
    displayName: 'Block of Gold',
    stackSize: 64,
    slot: 2
  },
  Item {
    type: 182,
    count: 26,
    metadata: 0,
    nbt: null,
    name: 'diamond_block',
    displayName: 'Block of Diamond',
    stackSize: 64,
    slot: 3
  },
  Item {
    type: 79,
    count: 46,
    metadata: 0,
    nbt: null,
    name: 'lapis_block',
    displayName: 'Lapis Lazuli Block',
    stackSize: 64,
    slot: 4
  },
  Item {
    type: 321,
    count: 56,
    metadata: 0,
    nbt: null,
    name: 'redstone_block',
    displayName: 'Block of Redstone',
    stackSize: 64,
    slot: 5
  },
  Item {
    type: 4,
    count: 17,
    metadata: 0,
    nbt: null,
    name: 'diorite',
    displayName: 'Diorite',
    stackSize: 64,
    slot: 6
  },
  Item {
    type: 2,
    count: 11,
    metadata: 0,
    nbt: null,
    name: 'granite',
    displayName: 'Granite',
    stackSize: 64,
    slot: 7
  },
  Item {
    type: 6,
    count: 28,
    metadata: 0,
    nbt: null,
    name: 'andesite',
    displayName: 'Andesite',
    stackSize: 64,
    slot: 8
  },
  Item {
    type: 580,
    count: 36,
    metadata: 0,
    nbt: null,
    name: 'gold_ingot',
    displayName: 'Gold Ingot',
    stackSize: 64,
    slot: 11
  },
  Item {
    type: 578,
    count: 38,
    metadata: 0,
    nbt: null,
    name: 'diamond',
    displayName: 'Diamond',
    stackSize: 64,
    slot: 12
  },
  Item {
    type: 695,
    count: 1,
    metadata: 0,
    nbt: null,
    name: 'lapis_lazuli',
    displayName: 'Lapis Lazuli',
    stackSize: 64,
    slot: 13
  },
  Item {
    type: 665,
    count: 10,
    metadata: 0,
    nbt: null,
    name: 'redstone',
    displayName: 'Redstone Dust',
    stackSize: 64,
    slot: 14
  },
  Item {
    type: 32,
    count: 27,
    metadata: 0,
    nbt: null,
    name: 'gravel',
    displayName: 'Gravel',
    stackSize: 64,
    slot: 16
  },
  Item {
    type: 9,
    count: 9,
    metadata: 0,
    nbt: null,
    name: 'dirt',
    displayName: 'Dirt',
    stackSize: 64,
    slot: 17
  },
  Item {
    type: 14,
    count: 3,
    metadata: 0,
    nbt: null,
    name: 'cobblestone',
    displayName: 'Cobblestone',
    stackSize: 64,
    slot: 26
  },
  Item {
    type: 39,
    count: 24,
    metadata: 0,
    nbt: null,
    name: 'birch_log',
    displayName: 'Birch Log',
    stackSize: 64,
    slot: 42
  },
  Item {
    type: 37,
    count: 47,
    metadata: 0,
    nbt: null,
    name: 'oak_log',
    displayName: 'Oak Log',
    stackSize: 64,
    slot: 43
  },
  Item {
    type: 573,
    count: 1,
    metadata: 0,
    nbt: null,
    name: 'apple',
    displayName: 'Apple',
    stackSize: 64,
    slot: 44
  },
  Item {
    type: 646,
    count: 54,
    metadata: 0,
    nbt: null,
    name: 'flint',
    displayName: 'Flint',
    stackSize: 64,
    slot: 48
  },
  Item {
    type: 613,
    count: 28,
    metadata: 0,
    nbt: null,
    name: 'stick',
    displayName: 'Stick',
    stackSize: 64,
    slot: 49
  },
  Item {
    type: 25,
    count: 12,
    metadata: 0,
    nbt: null,
    name: 'birch_sapling',
    displayName: 'Birch Sapling',
    stackSize: 64,
    slot: 51
  },
  Item {
    type: 23,
    count: 18,
    metadata: 0,
    nbt: null,
    name: 'oak_sapling',
    displayName: 'Oak Sapling',
    stackSize: 64,
    slot: 52
  },
  Item {
    type: 619,
    count: 13,
    metadata: 0,
    nbt: null,
    name: 'wheat_seeds',
    displayName: 'Wheat Seeds',
    stackSize: 64,
    slot: 53
  }
]
